'use strict';
class GardenAudio {
 constructor(){this.ctx=null;this.enabled=true;this.music=true;this.volume=.23;this.nextBeat=0;this.beat=0;this.lastShot=0;}
 init(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=this.volume;this.master.connect(this.ctx.destination);}if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});}catch{this.enabled=false;}}
 tone(freq,time=.15,type='sine',volume=.3,delay=0,endFreq){if(!this.enabled||!this.ctx)return;const t=this.ctx.currentTime+delay;const osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,t);if(endFreq)osc.frequency.exponentialRampToValueAtTime(endFreq,t+time);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,volume),t+.008);gain.gain.exponentialRampToValueAtTime(.0001,t+time);osc.connect(gain);gain.connect(this.master);osc.start(t);osc.stop(t+time+.04);osc.onended=()=>{osc.disconnect();gain.disconnect();};}
 noise(time=.25,volume=.4){if(!this.enabled||!this.ctx)return;const n=Math.ceil(this.ctx.sampleRate*time),b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/n,2);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=900;g.gain.value=volume;s.connect(f);f.connect(g);g.connect(this.master);s.start();s.onended=()=>{s.disconnect();f.disconnect();g.disconnect();};}
 play(name){if(!this.enabled||!this.ctx)return;switch(name){case'plant':this.tone(220,.12,'sine',.4,0,85);this.noise(.07,.1);break;case'collect':this.tone(660,.16,'sine',.35);this.tone(990,.28,'sine',.25,.08);break;case'shoot':if(this.ctx.currentTime-this.lastShot>.07){this.tone(360,.075,'sine',.12,0,140);this.lastShot=this.ctx.currentTime;}break;case'hit':this.tone(140,.035,'triangle',.055);break;case'kill':this.tone(150,.12,'triangle',.15,0,60);break;case'explode':this.noise(.65,.85);this.tone(110,.55,'sine',.75,0,28);break;case'click':this.tone(510,.055,'sine',.13);break;case'wave':[196,196,233,196].forEach((v,i)=>this.tone(v,.23,'triangle',.24,i*.19));break;case'mower':this.noise(.8,.6);this.tone(80,.9,'sawtooth',.12,0,120);break;case'chomp':this.tone(280,.18,'triangle',.3,0,65);break;case'won':[523,659,784,1047].forEach((v,i)=>this.tone(v,.5,'triangle',.3,i*.15));break;case'lost':[330,294,262,196].forEach((v,i)=>this.tone(v,.6,'triangle',.3,i*.28));break;}}
 update(active){if(!this.ctx||!this.enabled||!this.music||!active){this.nextBeat=0;return;}const now=this.ctx.currentTime;if(!this.nextBeat)this.nextBeat=now+.1;if(now>=this.nextBeat-.05){const melody=[76,0,79,0,74,0,72,0,76,79,81,79,74,0,0,0,72,0,76,0,71,0,67,0,69,72,74,72,67,0,0,0];const note=melody[this.beat%melody.length];const delay=Math.max(0,this.nextBeat-now);if(note)this.tone(440*Math.pow(2,(note-69)/12),.23,'sine',.15,delay);if(this.beat%4===0){const root=[48,53,45,55][Math.floor(this.beat/8)%4];this.tone(440*Math.pow(2,(root-69)/12),.48,'triangle',.11,delay);}this.beat++;this.nextBeat=now+.235;}}
}
